// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcM0C9h46p404mJZUJmmvGgbYwiKKdoA',
    appId: '1:547573172957:web:a309bbdf416edf07912934',
    messagingSenderId: '547573172957',
    projectId: 'last-task-330e2',
    authDomain: 'last-task-330e2.firebaseapp.com',
    storageBucket: 'last-task-330e2.appspot.com',
    measurementId: 'G-EKHWEG0KCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7-bhM3DW5RXsLBt-cKjNKriiZ-Fe48o',
    appId: '1:547573172957:android:0a667413017ccedc912934',
    messagingSenderId: '547573172957',
    projectId: 'last-task-330e2',
    storageBucket: 'last-task-330e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgrWckuGCdG5PieDKNE_JT27hzsyOSjIY',
    appId: '1:547573172957:ios:fbc6a934e93101fb912934',
    messagingSenderId: '547573172957',
    projectId: 'last-task-330e2',
    storageBucket: 'last-task-330e2.appspot.com',
    iosClientId: '547573172957-jgu1kdeot2qj1f70d2c59pb7ocnp52oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgrWckuGCdG5PieDKNE_JT27hzsyOSjIY',
    appId: '1:547573172957:ios:fbc6a934e93101fb912934',
    messagingSenderId: '547573172957',
    projectId: 'last-task-330e2',
    storageBucket: 'last-task-330e2.appspot.com',
    iosClientId: '547573172957-jgu1kdeot2qj1f70d2c59pb7ocnp52oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalTask',
  );
}
